// <auto-generated />
using System;
using Fiap.Api.Semaforos.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Api.Semaforos.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Semaforos.Models.CondicaoClimaticaModel", b =>
                {
                    b.Property<long>("CondicaoClimaticaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CondicaoClimaticaId"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<long>("SemaforoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<double>("Temperatura")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Tempo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("CondicaoClimaticaId");

                    b.HasIndex("SemaforoId");

                    b.ToTable("tbl_condicoes_climaticas", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.Semaforos.Models.FluxoVeiculoModel", b =>
                {
                    b.Property<long>("FluxoVeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FluxoVeiculoId"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<int>("Quantidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long>("SemaforoId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("FluxoVeiculoId");

                    b.HasIndex("SemaforoId");

                    b.ToTable("tbl_fluxo_veiculos", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.Semaforos.Models.SemaforoModel", b =>
                {
                    b.Property<long>("SemaforoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SemaforoId"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Luz")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("SemaforoId");

                    b.ToTable("tbl_semaforos", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.Semaforos.Models.UsuarioModel", b =>
                {
                    b.Property<long>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UsuarioId");

                    b.ToTable("tbl_usuarios", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.Semaforos.Models.CondicaoClimaticaModel", b =>
                {
                    b.HasOne("Fiap.Api.Semaforos.Models.SemaforoModel", "Semaforo")
                        .WithMany()
                        .HasForeignKey("SemaforoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semaforo");
                });

            modelBuilder.Entity("Fiap.Api.Semaforos.Models.FluxoVeiculoModel", b =>
                {
                    b.HasOne("Fiap.Api.Semaforos.Models.SemaforoModel", "Semaforo")
                        .WithMany()
                        .HasForeignKey("SemaforoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semaforo");
                });
#pragma warning restore 612, 618
        }
    }
}
